### ISSUE TITLE
FareCalculator Algorithm

### ISSUE THREAD

**Issue by sehoven** [CMPUT301F16T01/Carrier#103]
The FareCalcultor is producing astronomical values for the routes. We should play with the constants to find a more reasonable algorithm.

**Comment by sehoven** [comment]
@kieter Maybe you want to play around with this since you wrote the algorithm?

**Comment by kieter** [comment]
Sure. I'll check it out today.

**Comment by sehoven** [comment]
My branch **user-request-view-location** is where this is linked up so that's where you should go to test it out (there's a pull request but it's not in master yet).

**Comment by kieter** [comment]
Closing because I'm silly and forgot to divide calculatedFare by 10.

**Comment by MandyMeindersma** [comment]
Which branch is the final fare calculator on?

**Comment by sehoven** [comment]
user-request-view-location and user-view-request (both waiting to be merged)

**Comment by MandyMeindersma** [comment]
Is fare calculator good? the comments say it still needs things?

like:
/\* TODO: once we get routing working on our map we'll fetch the distance and duration */

**Comment by sehoven** [comment]
That has been removed. That TODO was complete.
