### ISSUE TITLE
Clickable Username Bug

### ISSUE THREAD

**Issue by sehoven** [CMPUT301F16T01/Carrier#107]
For the clickable user name, the edit button works for email, but not for phone number.

**Comment by kieter** [comment]
Fixed in 4e17173d11e86e5ade7d9c0be1acc05d609307e3. I accidentally made the email be the phone number haha.

**Comment by kieter** [comment]
Reopened because I closed the wrong issue.

**Comment by MandyMeindersma** [comment]
@kieter you fixed this right?
