### ISSUE TITLE
change start and end instead of to and from

### ISSUE THREAD

**Issue by MichaelParadis** [CMPUT301F16T01/Carrier#133]
Should make the order of the locations on the adapter and the viewing of request activity consistent. 
See attached screenshots.
![screenshot_20161115-125511](https://cloud.githubusercontent.com/assets/17303106/20321685/920389f6-ab33-11e6-9091-34c56c34aed7.png)
![screenshot_20161115-125520](https://cloud.githubusercontent.com/assets/17303106/20321698/97cf520c-ab33-11e6-91b0-5b36ae9a509e.png)

**Comment by MichaelParadis** [comment]
Nevermind I can not read.

**Comment by MandyMeindersma** [comment]
I fixed it. See my pull request

**Comment by sehoven** [comment]
Merged [#157](https://github.com/CMPUT301F16T01/Carrier/pull/157)
