### ISSUE TITLE
Generalize RequestList 

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#162]
Make it so that it can use any object and listen

**Comment by MandyMeindersma** [comment]
- "RequestList" does not appear to be specifically tailored for dealing with the Request class. It does not use any of Request's methods. More so, it only overrides one method of the ArrayList, #add, where the List interface exposes several mutation methods (#clear, #addAll, #remove, etc.). Ways to improve:
  - Make it generic: it doesn't seem to care that it's dealing with Request objects at all.
  - Perhaps allow use the decorator pattern to decorate a List<> with the ability to observe mutation operations
  - Both of these actions will greatly increase code reuse, but do them only if it seems necessary in your app (how many different kind of observable Lists do you need?)

**Comment by MandyMeindersma** [comment]
though out many commits during the past two weeks I feel we have completed this. @sehoven

**Comment by Hreherch** [comment]
Not quite. The feedback was to change RequestList to a decorator pattern which we could do but haven't exactly. We did add one method that is more tailored to requests though (the id containing check).. but htat's all we have done

**Comment by MandyMeindersma** [comment]
For offline we have added a ton of methods that are more specialized to deal with requests (will be pushed in a half hour)

Although it is not decorator it is addressing most feedback
