### ISSUE TITLE
Flush cached files when user logs out online

### ISSUE THREAD

**Issue by sehoven** [CMPUT301F16T01/Carrier#208]
On the log in screen when the user is online, flush the cached files (RIDER_FILENAME and DRIVER_FILENAME in RequestController). This is because we don't want to keep data saved from a previous user when we log into a new user.

**Comment by Hreherch** [comment]
Still unsure if this is necessary? Since we flush the requests to elastic search properly, it just looks really weird for some minor edge case. And since the edge case is very edgy, I'm putting this as "will not fix"
