### ISSUE TITLE
Project Part 2: Release Planning

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#33]
The Release Planning section of the wiki is confusing. It doesn't clarify that "These are the tasks we wish to do for project part 4" (or 5) and we should specify our "pick use cases that we think we can accomplish and do 5-6 a week" strategy. It is also very inconsistent, including midterms (do we need to track this specifically on the wiki?) but also sometime not including them. I also believe every "week" or "meeting heartbeat" should be a header.

**Comment by Hreherch** [comment]
I included an example timeline from one of my classes in our Google Doc folder:
https://docs.google.com/document/d/1CY2mKI1FFW2Wg-b75PRn3uTrobr7AYFPiMKJ6PKa04Q/

**Comment by MandyMeindersma** [comment]
I made it look a little prettier

**Comment by Hreherch** [comment]
Finished this earlier.
