### ISSUE TITLE
Project Part 2: Individual and Peer Assessment

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#34]
Each member must complete an assessment form to describe his or her individual contribution to the project for this stage, and to review the performance of the other members.
- [x] @MandyMeindersma 
- [x] @MichaelParadis 
- [ ] @sehoven 
- [x] @kieter 
- [x] @hreherch

**Comment by kieter** [comment]
This is to be done after we hand in this part of the project thank god 🙏 
https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=712676

**Comment by Hreherch** [comment]
@sehoven Make sure you check yourself off, it's due on the 20th! :)

**Comment by Hreherch** [comment]
Hopefully everyone did it.
