### ISSUE TITLE
Implement US 03.03.01 (present user information when clicking on username)

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#39]
As a user, I want to, when a username is presented for a thing, retrieve and show its contact information.
- [x] May require creating a button class that pulls up an instance of a user profile (without editing permission) or a dialogue that appears showing the information. 
- [x] Clarify/remove ambiguity that this is what we need to do (with Abram or @eddieantonio) 

*\* IMPORTANT: This case effects the WHOLE program. Every time a username is pressed this must happen. **

**Comment by eddieantonio** [comment]
All requirement clarifications should be directed at the client; that is, Abram. Post it on the forum!

**Comment by Hreherch** [comment]
> When a user is being displayed or their username, we should be able to get details about the user.
> Thing could be a request or a confirmation or kind of user associated event.

src: https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=714028

**Comment by Hreherch** [comment]
Currently in progress, being merged. see: #88
