### ISSUE TITLE
Login Activity

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#40]
Requirements:
- [x] User can specify a unique username to login with
- [x] Need to remove references to logging in a rider xor driver

Other:
- [x] XML for logging in
- [x] LoginActivity
- [x] Links to Driver or Rider activity

**Comment by kieter** [comment]
Mike is going to review my code and I will review his 😃

**Comment by kieter** [comment]
Did it! Bennett connected it to Driver/Rider activity 💯

**Comment by Hreherch** [comment]
Notes on why this was reopened:
1. Was not reviewed/pull requested into master
2. Implementation is not final (Need to remove password references and change the overall design to fit manager feedback)

**Comment by Hreherch** [comment]
Closing, see pull request #65.
