### ISSUE TITLE
Project Part 2 Response Item: Remove Passwords

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#45]
- [x] Remove passwords in general
- [x] Allow for transfer between the rider and driver activities in their respective option menus

**Comment by Hreherch** [comment]
Removed references from user-visible things (i.e. LoginActivity) in rider-xml
needs pruning from code areas

**Comment by kieter** [comment]
Did it! The string "password" doesn't even show up in our project anymore 😄.
