### ISSUE TITLE
Project Part 2 Response Item: Update use cases

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#46]
- [x] "Request 5" : user case should reflect that we contact the driver by email/phone, NOT bring up the information.
- [x] "Please specify an alternate flow for exceptional cases."
- [x] Fare estimations should be automatic (i.e. already in the box). the user need not press a button (but it can be available in case they change it by accident)

**Comment by MichaelParadis** [comment]
I will change use cases to reflect the fare estimates being automatic.

**Comment by Hreherch** [comment]
I added a exception flow and fixed the post condition for Request5

**Comment by MichaelParadis** [comment]
Made it more clear that fare estimation is automatic.
