### ISSUE TITLE
Mock Up

### ISSUE THREAD

**Issue by MandyMeindersma** [CMPUT301F16T01/Carrier#51]
Make the mock up be an accurate reflection of our project

**Comment by MandyMeindersma** [comment]
I think it is somewhat finished... check the box if you have looked at it and liked it:
- [ ] @sehoven 
- [x] @kieter  
- [x] @Hreherch 
- [x] @MichaelParadis 

Leave comments on things that need to be changed?

**Comment by Hreherch** [comment]
Looking good! :>

I just realized that it meant messaging for "contacting"? I thought maybe you could automatically call them with some button? So we need a way to view messages for each user?
How do we signify that a red light for a rider is possibly different than a red light for a driver? 
Why is "see requests" a menu item?
Can we add toggle buttons to the top of a rider's current requests? (i.e. you can toggle showing cancelled, open, waiting, and complete requests)
How are we indicating that request was accepted? (dialogue boxes?)

**Comment by MandyMeindersma** [comment]
About the contacting: a message would be sent through email? (Therefore we do not have to deal with messages)  And a phone call button should be added. 

If we do icons, we should probably display a legend? Where? How?

I will delete "see requests"

I will add some toggle buttons, not quite sure how to make them pretty though... any ideas? What's your XML looking like (I'll check later)

Requests will be accepted through dialogue boxes, it's just awkward to show that in a mock up. Is that okay?

**Comment by Hreherch** [comment]
That makes sense. But we'd need to be able to send them an email somehow in Java. I think we should ask if we need to have the phone screen or email application of the phone appear?
Maybe a setting for help? In the Wiki? Both? More? 
My XML looks bad, lol. 
Yeah, just remembered you did it in the story anyway

**Comment by MandyMeindersma** [comment]
Mostly everyone reviewed it. I will add it to the wiki

**Comment by Hreherch** [comment]
Closing, as it has been changed according to feedback and brought up to current expectations
