### ISSUE TITLE
Rider can cancel a request

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#61]
Please implement this feature. 
Due: Oct 31.

Coder: Mike
Code Review: Mandy

**Comment by MandyMeindersma** [comment]
You need to be able to see a request first... I am working on that right now...

**Comment by MandyMeindersma** [comment]
I got stuck

**Comment by MandyMeindersma** [comment]
you can see it from my branch show-request-status branch
