### ISSUE TITLE
Permanence in editing profile

### ISSUE THREAD

**Issue by Hreherch** [CMPUT301F16T01/Carrier#67]
Need to add a way to change the loggedInUser in elastic search when they alter their name in app. Currently, the user is edited but the elastic search is not (edits will not persist after closing and reopening app).

**Comment by MichaelParadis** [comment]
I think the best way to do this would be following the observer pattern that will have the observers tell the elastic controller to update relevant information in a user's profile and possibly have it work that way for updating everything in elastic controller to reduce duplicate code and follow OO design practices..

**Comment by Hreherch** [comment]
Or the view could tell UserController to modify the user data (which would both change logged in user and elastic search)?

**Comment by kieter** [comment]
Finished in 4e17173d11e86e5ade7d9c0be1acc05d609307e3
