### ISSUE TITLE
Can add users with whitespace/non-letter usernames

### ISSUE THREAD

**Issue by kieter** [CMPUT301F16T01/Carrier#68]
When you register you are able create usernames with only special characters (()!@#$%^&*...) and whitespace (   ). I guess usernames should only be letters (a-z), numbers (0-9), underscores (_) and dashes (-).

See pull request #65.

**Comment by Hreherch** [comment]
Added a whitespace fix in #65.
I think non alpha-num chars are fine otherwise?

**Comment by Hreherch** [comment]
Merged.
