### ISSUE TITLE
View User Profile UI 

### ISSUE THREAD

**Issue by sehoven** [CMPUT301F16T01/Carrier#70]
When you view a user profile, the edit button (and the save/delete changes buttons once they're visible) overlaps with the email/phone number text boxes even when they're not that long. This makes it difficult when the user is editing a long string to select the end of the edit text box. 

Could we move these buttons further to the right and have them **not** overlap with the edit text box?

**Comment by sehoven** [comment]
The input type for the email edit text is **android:inputType="none|textEmailAddress"** in the XML, however the email keyboard (with the @ and . symbols on the front) is not showing up. Do we need the **none|** part?

**Comment by sehoven** [comment]
The input type for the phone number edit text is **android:inputType="number|phone"** in the XML. I know for creating a new user the input type is just **number**. Is there a reason this is different here?

**Comment by kieter** [comment]
I'll take a look at this.

**Comment by Hreherch** [comment]
@kieter just a reminder that you mentioned you were on this.

**Comment by kieter** [comment]
I fixed this in f3469c5a525d1e7335af02447e12f9cfb1fb3a79. They don't overlap anymore 👍.
